version: "3.7"

services:
  proxy:
    image: traefik:1.7.9-alpine
    command:
      - "--docker"
      - "--docker.domain=${DOCKER_URL}"
    env_file:
     - .env
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      - "traefik.backend=traefik"
      - "traefik.docker.network=traefik"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:${ADMIN_URL}"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.auth.basic=${ADMIN_USERNAME}:${ADMIN_PASSWORD}"
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik
